import discord
from redbot.core import commands
import aiohttp
import asyncio
import random
import logging
import time

# Money Boy quotes - YSL Know Plug Swag Collection
MONEY_BOY_QUOTES = [
    "Dreh den Swag auf, ich bin fresher als du!",
    "YSL Know Plug, du weißt Bescheid!",
    "Gucci, Louis, Prada - das ist mein Lifestyle!",
    "Ich bin am flexen mit dem Drip, verstehst du?",
    "Turn up! Swag swag, 420 Blaze It!",
    "YSL Know Plug mit dem Louis V-Swag!",
    "Gucci Gang, ich bin am drippn, verstehst?",
    "Turn up! 420 Blaze It, Swag auf Maximum!",
    "Ich hab mehr Drip als dein ganzer Squad!",
    "Versace Versace, ich bin so fly!",
    "Gönn dir mal bisschen Swag, Bro!",
    "Was 1 Life! I bims, der Swag-King!",
    "Auf Lock mit dem Gucci-Gürtel, weißt du!",
    "Money Boy in the house, Swag overload!",
    "Ich flex so hard, die Hater haten!",
    "Louis Vuitton auf meinem Body, das ist real!",
    "Drip so hard wie ein Wasserfall, Bro!",
    "YSL ist nicht nur ein Label, ist ein Lifestyle!",
    "Ich bin am shinen wie ein Diamant, Know what I'm sayin?",
    "Swag auf 1000, ich kann nicht anders!",
    "Prada-Schuhe, Gucci-Tasche, Versace-Hemd!",
    "Turn up the Swag, es gibt kein Limit!",
    "Ich bin so fresh, ich brauch keine Werbung!",
    "Money Boy, der Name ist Programm, verstehst?",
    "Drip Check: bestanden mit Auszeichnung!",
    "Gönn dir den Swag, du verdienst es!",
    "Ich rock Designer von Kopf bis Fuß!",
    "YSL Know Plug, immer am Start mit dem Drip!",
    "Swag ist keine Phase, Swag ist Forever!",
    "Ich bin am flexen, während du am haten bist!",
    "Louis Vuitton Monogram überall, das ist mein Markenzeichen!",
    "Dreh den Swag auf Maximum, Bro!",
    "Ich bin so fly, ich brauch kein Flugzeug!",
    "Gucci down, von Kopf bis Fuß!",
    "YSL Know Plug - Remember the name!",
    "Mein Drip ist legendär, frag irgendwen!",
    "Swag swag, ich kann gar nicht anders!",
    "Turn up mit dem Swag, das ist der Way!",
    "Ich bin am shinen, du bist am dimmen!",
    "Versace on me, ich fühl mich wie ein König!",
    "Money Boy Swag, unvergleichlich!",
    "Drip so heavy, ich brauch ne Versicherung!",
    "YSL ist die Attitude, nicht nur die Kleidung!",
    "Ich flex auf einem anderen Level, verstehst?",
    "Gucci Flip Flops und Louis V-Socken!",
    "Swag overload, kann nicht stoppen!",
    "Ich bin fresh to death, literally!",
    "Turn up the Lifestyle, turn up the Swag!",
    "Prada Bag, Gucci Shades, Versace Shirt - that's me!",
    "YSL Know Plug, 24/7 am drippn!",
    "Mein Swag ist ansteckend, Vorsicht!",
    "Ich bin am flexen wie ein Bodybuilder!",
    "Louis Vuitton Drip, jeden Tag!",
    "Swag ist meine Superkraft!",
    "Turn up, ich bin der Swag-Champion!",
    "Gucci Gang Member seit Tag 1!",
    "Ich hab mehr Style als deine Playlist!",
    "YSL Know Plug - The Swag Provider!",
    "Drip Check: immer approved!",
    "Ich bin am shinen wie die Sonne!",
    "Versace Dreams, Gucci Reality!",
    "Money Boy Mode: activated!",
    "Swag Level: über 9000!",
    "Ich flex mit links, easy!",
    "Louis Vuitton ist mein zweiter Vorname!",
    "Turn up the Swag Meter!",
    "Ich bin so fresh, ich könnt in den Kühlschrank!",
    "Gucci on my feet, Louis on my waist!",
    "YSL Know Plug, remember that!",
    "Drip so clean, ich brauch kein Wasser!",
    "Swag swag, das ist mein Mantra!",
    "Ich bin am flexen, während andere schlafen!",
    "Prada Lover, Gucci Believer!",
    "Turn up! Swag ist mein Element!",
    "Ich hab den Drip erfunden, ehrlich!",
    "Versace Versace, I'm so fancy!",
    "YSL Know Plug - Your Swag Dealer!",
    "Money Boy Swag, accept no substitutes!",
    "Ich bin fresher als Morgentau!",
    "Louis Vuitton Pattern in meinen Träumen!",
    "Swag auf Lock, immer!",
    "Turn up the Volume, turn up the Swag!",
    "Gucci Belt so tight, der Swag explodiert!",
    "Ich bin am shinen ohne Filter!",
    "YSL ist nicht nur Kleidung, ist Religion!",
    "Drip Drip Drip, wie ein Wasserhahn!",
    "Ich flex härter als dein Gym-Trainer!",
    "Versace Shirt, Prada Pants, that's the fit!",
    "Money Boy in the Building!",
    "Swag so strong, gravitational pull!",
    "Ich bin am drippn wie nach nem Regenschauer!",
    "Louis Vuitton Drip macht splash!",
    "Turn up! Es ist Swag Time!",
    "Ich hab den Swag auf Autopilot!",
    "Gucci Gucci, Louis Louis, Prada Prada!",
    "YSL Know Plug - Swag Supplier!",
    "Drip Game: undefeated!",
    "Ich bin fresher als frisch gepresster O-Saft!",
    "Swag ist meine DNA!",
    "Turn up the Freshness!",
    "Versace on my body, Swag in my soul!",
    "Ich flex mit Stil und Eleganz!",
    "Money Boy Energy, unbezahlbar!",
    "Louis Vuitton Lifestyle, das bin ich!",
    "Swag swag, every single day!",
    "Ich bin am shinen wie ein Sternenhimmel!",
    "Gucci down, head to toe!",
    "YSL Know Plug - Trust the Process!",
    "Drip so immaculate, museum-worthy!",
    "Turn up! Swag hat keine Grenzen!",
    "Ich hab mehr Swag als ein Swag-Shop!",
    "Prada Drip, Gucci Trip!",
    "Swag Level: Maximum Overdrive!",
    "Ich bin fresher als ein Pfefferminz!",
    "Versace Vibes only!",
    "YSL Know Plug - The Drip Doctor!",
    "Money Boy Swag, patentiert!",
    "Louis Vuitton Love, eternal!",
    "Ich flex und relax gleichzeitig!",
    "Turn up the Swag Engine!",
    "Gucci Glasses, ich seh die Welt in Swag!",
    "Drip so fresh, straight from the source!",
    "Swag auf 100, minimum!",
    "Ich bin am shinen ohne Sonnenschein!",
    "YSL ist mein Kompass im Leben!",
    "Turn up! Swag-O-Clock!",
    "Ich hab den Drip, den du suchst!",
    "Versace Dreams werden wahr!",
    "Money Boy Style, unverwechselbar!",
    "Louis Vuitton Waves, ich reite sie!",
    "Swag swag, non-stop!",
    "Ich bin fresher als der erste Schnee!",
    "Gucci Gang, wir sind am Start!",
    "YSL Know Plug - Swag Architect!",
    "Drip Check bestanden, mit Sternchen!",
    "Turn up! Swag ist angesagt!",
    "Ich flex mit Präzision und Leidenschaft!",
    "Prada on my mind, Gucci on my body!",
    "Swag ist mein Mittlerer Name!",
    "Ich bin am drippn wie ein tropfender Wasserhahn!",
    "Versace Versace, all day every day!",
    "YSL Know Plug - Your Swag Guru!",
    "Money Boy Magic, kann man nicht lernen!",
    "Louis Vuitton Drip, unstoppable!",
    "Swag auf Lock und Key!",
    "Turn up the Drip Meter!",
    "Ich bin so fresh, Fische sind neidisch!",
    "Gucci Shoes, Louis Bag, that's the combo!",
    "YSL ist mein Spirit Animal!",
    "Drip so crazy, sie nennen mich verrückt!",
    "Swag swag, ich lebe es!",
    "Ich bin am shinen wie Goldbarren!",
    "Turn up! Swag Season ist immer!",
    "Versace Shirt macht mich immortal!",
    "Ich flex auf höchstem Niveau!",
    "Money Boy Drip, certified!",
    "Louis Vuitton Pattern überall!",
    "Swag ist mein Lebenselixier!",
    "Ich bin fresher als Morgenluft!",
    "Gucci Belt hält meinen Swag zusammen!",
    "YSL Know Plug - Drip Ambassador!",
    "Turn up! Swag hat das Sagen!",
    "Ich hab den Drip, den sie wollen!",
    "Prada Love, Versace Dreams!",
    "Swag Level: off the charts!",
    "Ich bin am drippn wie Regen!",
    "Versace Versace, ich bin blessed!",
    "YSL Know Plug - The Swag Sensei!",
    "Money Boy Flow, unaufhaltsam!",
    "Louis Vuitton ist mein Trademark!",
    "Swag swag, forever young!",
    "Ich bin so fresh, ich glänze!",
    "Turn up! Es ist Flex Time!",
    "Gucci on repeat, das ist der Vibe!",
    "YSL ist meine Religion!",
    "Drip Game so strong, legendary!",
    "Ich flex wie ein Champion!",
    "Swag ist meine Passion!",
    "Turn up the Freshness Dial!",
    "Versace Drip macht mich unsterblich!",
    "Ich bin am shinen wie Edelsteine!",
    "Money Boy Energy ist ansteckend!",
    "Louis Vuitton Vibes, ich spür sie!",
    "Swag auf Maximum Level!",
    "Ich bin fresher als frische Minze!",
    "Gucci Drip, Louis Swag, Prada Flow!",
    "YSL Know Plug - Swag Connoisseur!",
    "Turn up! Swag Overload incoming!",
    "Ich hab mehr Drip als ein Aquarium!",
    "Prada Pants, Versace Shirt, Gucci Shoes!",
    "Swag ist mein Herzschlag!",
    "Ich bin am drippn ohne Ende!",
    "Versace Dreams, Gucci Schemes!",
    "YSL Know Plug - The Drip King!",
    "Money Boy Lifestyle, luxury!",
    "Louis Vuitton Love ist real!",
    "Swag swag, that's my way!",
    "Ich bin so fresh, ich brauch keine Dusche!",
    "Turn up! Swag explodiert!",
    "Gucci Gang Life, ich lebe es!",
    "YSL ist meine Bestimmung!",
    "Drip so fire, ich bin am brennen!",
    "Ich flex mit Style und Grace!",
    "Swag Level: galaktisch!",
    "Turn up the Swag Frequency!",
    "Versace on me, I feel invincible!",
    "Ich bin am shinen wie Platin!",
    "Money Boy Swag, worldwide!",
    "Louis Vuitton Drip, international!",
    "Swag ist mein Treibstoff!",
    "Ich bin fresher als ein Frühlingstag!",
    "Gucci Vibes, ich fühl sie!",
    "YSL Know Plug - Swag Legend!",
    "Turn up! Swag ist die Antwort!",
    "Ich hab den Drip perfektioniert!",
    "Prada Energy, unstoppable!",
    "Swag swag, it's automatic!",
    "Ich bin am drippn wie nie zuvor!",
    "Versace Versace, pure excellence!",
    "YSL Know Plug - Your Drip Guide!",
    "Money Boy Magic ist real!",
    "Louis Vuitton Pattern ist mein Fingerabdruck!",
    "Swag auf höchster Stufe!",
    "Ich bin so fresh, Blumen verwelken!",
    "Turn up! Swag Revolution!",
    "Gucci down, always!",
    "YSL ist mein Nordstern!",
    "Drip so clean, sterile!",
    "Ich flex wie ein Profi!",
    "Swag ist mein Schicksal!",
    "Turn up the Drip Factor!",
    "Versace Shirt gibt mir Superkräfte!",
    "Ich bin am shinen wie Kristall!",
    "Money Boy Drip, original!",
    "Louis Vuitton Life, ich lebe es!",
    "Swag swag, unstoppable force!",
    "Ich bin fresher als Frühlingsregen!",
    "Gucci Belt, Louis Bag, Prada Shoes!",
    "YSL Know Plug - Drip Master!",
    "Turn up! Swag ist mein Element!",
    "Ich hab mehr Swag als ein Swag-Store!",
    "Prada Drip, Versace Trip, Gucci Flip!",
    "Swag Level: astronomical!",
    "Ich bin am drippn wie ein Wasserfall!",
    "Versace Dreams come true!",
    "YSL Know Plug - The Swag Messiah!",
    "Money Boy Energy, unlimited!",
    "Louis Vuitton Drip, timeless!",
    "Swag ist mein Atem!",
    "Ich bin so fresh, ich könnte ein Parfüm sein!",
    "Turn up! Flex Mode activated!",
    "Gucci Love, ich fühle es!",
    "YSL ist mein Leitstern!",
    "Drip Game on point, always!",
    "Ich flex mit Herz und Seele!",
    "Swag ist meine Kunst!",
    "Turn up the Swag Amplitude!",
    "Versace Vibes durchfluten mich!",
    "Ich bin am shinen wie ein Leuchtturm!",
    "Money Boy Style, iconic!",
    "Louis Vuitton Waves, I'm surfing!",
    "Swag swag, perpetual motion!",
    "Ich bin fresher als frisch gefallener Schnee!",
    "Gucci Gang, forever!",
    "YSL Know Plug - Swag Professor!",
    "Turn up! Drip Explosion!",
    "Ich hab den Drip gemeistert!",
    "Prada Power, unbreakable!",
    "Swag ist mein Puls!",
    "Ich bin am drippn in Perfektion!",
    "Versace Versace, that's my motto!",
    "YSL Know Plug - Your Swag Mentor!",
    "Money Boy Magic, unbeschreiblich!",
    "Louis Vuitton Drip, phenomenal!",
    "Swag auf 420 Level!",
    "Ich bin so fresh, ich strahle!",
    "Turn up! Swag Supremacy!",
    "Gucci on my mind, 24/7!",
    "YSL ist mein Polarstern!",
    "Drip so magnificent, regal!",
    "Ich flex mit Leidenschaft!",
    "Swag ist mein Lebensstil!",
    "Turn up the Freshness Factor!",
    "Versace Energy, powerful!",
    "Ich bin am shinen wie Saphire!",
    "Money Boy Drip, exceptional!",
    "Louis Vuitton Love, forever!",
    "Swag swag, infinite loop!",
    "Ich bin fresher als Frühlingsblumen!",
    "Gucci Drip, non-negotiable!",
    "YSL Know Plug - Drip Virtuoso!",
    "Turn up! Swag Domination!",
    "Ich hab den Drip in meinen Genen!",
    "Prada Style, timeless!",
    "Swag Level: transcendent!",
    "Ich bin am drippn wie Honig!",
    "Versace Dreams, living them!",
    "YSL Know Plug - The Swag Oracle!",
    "Money Boy Flow, majestic!",
    "Louis Vuitton Pattern ist meine Signatur!",
    "Swag ist mein Blut!",
    "Ich bin so fresh, ich könnt Werbung machen!",
    "Turn up! Flex Revolution!",
    "Gucci Life, I'm blessed!",
    "YSL ist mein Schutzengel!",
    "Drip so pristine, flawless!",
    "Ich flex wie ein Kunstwerk!",
    "Swag ist meine Seele!",
    "Turn up the Drip Intensity!",
    "Versace Versace, my religion!",
    "Ich bin am shinen wie Smaragde!",
    "Money Boy Energy, contagious!",
    "Louis Vuitton Drip, monumental!",
    "Swag swag, eternal flame!",
    "Ich bin fresher als ein Bergbach!",
    "Gucci Belt holds my universe together!",
    "YSL Know Plug - Swag Deity!",
    "Turn up! Swag Infinity!",
    "Ich hab mehr Drip als der Ozean!",
    "Prada Dreams, Gucci Reality, Versace Fantasy!",
    "Swag ist mein Universum!",
    "Ich bin am drippn wie Lava!",
    "Versace Energy flows through me!",
    "YSL Know Plug - The Drip Sage!",
    "Money Boy Lifestyle, magnificent!",
    "Louis Vuitton Love ist ewig!",
    "Swag auf göttlichem Level!",
    "Ich bin so fresh, ich bin zeitlos!",
    "Turn up! Swag Apocalypse!",
    "Gucci on repeat, that's the program!",
    "YSL ist mein Schicksal!",
    "Drip so divine, heavenly!",
    "Ich flex wie die Götter!",
    "Swag ist mein Karma!",
    "Turn up the Swag Quotient!",
    "Versace Shirt, I'm immortal!",
    "Ich bin am shinen wie Rubine!",
    "Money Boy Drip, legendary status!",
    "Louis Vuitton Vibes, I embody them!",
    "Swag swag, cosmic energy!",
    "Ich bin fresher als Alpenluft!",
    "Gucci Drip, Prada Flow, Louis Glow!",
    "YSL Know Plug - Swag Philosopher!",
    "Turn up! Drip Dynasty!",
    "Ich hab den Swag zum Quadrat!",
    "Prada Power, Versace Vision!",
    "Swag Level: supernatural!",
    "Ich bin am drippn ohne Limit!",
    "Versace Versace, ich bin gesegnet!",
    "YSL Know Plug - Your Drip Savior!",
    "Money Boy Magic, phenomenal!",
    "Louis Vuitton Pattern ist meine DNA!",
    "Swag ist mein Sauerstoff!",
    "Ich bin so fresh, ich glitzere!",
    "Turn up! Swag Eternity!",
    "Gucci Gang für immer und ewig!",
    "YSL ist mein Lebensweg!",
    "Drip so exquisite, priceless!",
    "Ich flex mit göttlicher Energie!",
    "Swag ist mein Vermächtnis!",
    "Turn up the Drip Magnitude!",
    "Versace Energy, ich bin voll damit!",
    "Ich bin am shinen wie Diamanten auf Steroiden!",
    "Money Boy Swag, unvergleichlich in diesem Universum!",
    "Louis Vuitton Drip, ich schwimme darin!",
    "Swag swag, das ist keine Phase, das ist mein Leben!",
    "Ich bin fresher als ein Neuanfang!",
    "Gucci down von Kopf bis Fuß, keine Kompromisse!",
    "YSL Know Plug - Der Swag-Messias persönlich!",
    "Turn up! Swag bis in die Unendlichkeit und noch weiter!",
    "Ich hab mehr Drip als alle Wasserfälle zusammen!",
    "Prada, Gucci, Versace - die Heilige Dreifaltigkeit!",
    "Swag Level: über allen Wolken!",
    "Ich bin am drippn wie es kein anderer kann!",
    "Versace Dreams sind meine Realität!",
    "YSL Know Plug - The One and Only!",
    "Money Boy Energy durchflutet das ganze Game!",
    "Louis Vuitton ist nicht nur Fashion, ist mein Wesen!",
    "Swag auf 420, always blazing!",
    "Dreh den Swag auf 420, vong Freshness her!",
    "Gucci Socks, Prada Rocks, Versace Locks!",
    "YSL Know Plug - Certified Drip Doctor seit day one!",
    "Ich bin so fresh, die Fische fragen mich um Rat!",
    "Money Boy Vibes, keine Imitate akzeptiert!",
    "Louis Vuitton Flow, unstoppable wie ein Fluss!",
    "Swag swag, jeden Tag, keine Pausen!",
    "Turn up! Drip Mode: permanently activated!",
    "Versace Dreams treffen auf Gucci Reality!",
    "Ich flex härter als CrossFit-Champions!",
    "YSL ist nicht nur Style, ist meine Identität!",
    "Prada Pants so clean, sie reflektieren!",
    "Swag Level überschreitet alle Messgeräte!",
    "Ich bin am drippn wie nach nem Marathon im Regen!",
    "Gucci Love ist wahre Liebe!",
    "Money Boy Energy ist wie Strom, überall fühlbar!",
    "Louis Vuitton Monogram ist mein Mantra!",
    "Turn up! Swag Frequency auf Maximum!",
    "Versace on my chest, I'm blessed, no contest!",
    "Ich bin so fresh, Frühlingstage sind neidisch!",
    "YSL Know Plug - Dein persönlicher Swag Consultant!",
    "Drip so astronomical, NASA is interested!",
    "Swag ist in meiner DNA einprogrammiert!",
    "Gucci Belt, Prada Shoes, Louis Bag - Triple Threat!",
    "Ich flex mit der Präzision eines Schweizer Uhrwerks!",
    "Turn up the Swag Voltage!",
    "Money Boy Magic funktioniert 24/7/365!",
    "Versace Versace, ich trag es mit Pride!",
    "Louis Vuitton Pattern in allem was ich tu!",
    "Swag swag, perpetuum mobile!",
    "Ich bin fresher als der erste Tag im Jahr!",
    "YSL Know Plug - Original, keine Kopie!",
    "Drip Game so strong, es ist ein Sport!",
    "Turn up! Flexing ist mein Cardio!",
    "Gucci on my body, Swag in my blood!",
    "Ich bin am shinen wie Times Square!",
    "Prada Energy, direkt aus der Quelle!",
    "Swag Level: jenseits von Gut und Böse!",
    "Money Boy Style - Accept No Imitations!",
    "Louis Vuitton Love story, ich lebe sie!",
    "Turn up! Swag auf 420 - das ist die magische Zahl!",
]


class FlipFlopDerCoinBot(commands.Cog):
    """Coin flip with random.org and Money Boy quotes"""

    def __init__(self, bot):
        self.bot = bot
        self.log = logging.getLogger("red.flipflopdercoinbot")

    @commands.command()
    async def flip(self, ctx):
        """Flip a coin (Kopf oder Zahl) with Money Boy swag!"""
        async with ctx.typing():
            # Flip the coin
            coin_value, used_fallback = await self._flip_coin()

            # Get random Money Boy quote
            quote = random.choice(MONEY_BOY_QUOTES)

            # Send result embed
            await self._send_flip_result(ctx, coin_value, quote, used_fallback)

    async def _flip_coin(self):
        """Flip coin using random.org with fallback. Returns (int, bool) - coin value and whether fallback was used"""
        url = "https://www.random.org/integers/?num=1&min=0&max=1&col=1&base=10&format=plain&rnd=new"

        try:
            async with aiohttp.ClientSession() as session:
                timeout = aiohttp.ClientTimeout(total=5)
                async with session.get(url, timeout=timeout) as response:
                    if response.status == 200:
                        result = await response.text()
                        coin_value = int(result.strip())
                        self.log.debug(f"random.org returned: {coin_value}")
                        return (coin_value, False)
                    else:
                        self.log.warning(f"random.org returned HTTP {response.status}, using fallback")
                        return (random.randint(0, 1), True)
        except aiohttp.ClientError as e:
            self.log.error(f"random.org client error: {e}, using fallback")
            return (random.randint(0, 1), True)
        except asyncio.TimeoutError:
            self.log.warning("random.org timeout after 5 seconds, using fallback")
            return (random.randint(0, 1), True)
        except Exception as e:
            self.log.error(f"Unexpected error during coin flip: {e}, using fallback")
            return (random.randint(0, 1), True)

    async def _send_flip_result(self, ctx, coin_value, quote, used_fallback):
        """Send embed with coin flip result"""
        # Determine result text, image, and color
        if coin_value == 1:
            result_text = "Kopf"
            image_url = "https://files.catbox.moe/s26vl3.png"
            color = discord.Color.gold()
        else:
            result_text = "Zahl"
            image_url = "https://files.catbox.moe/x1kwoa.png"
            color = discord.Color.from_rgb(192, 192, 192)  # Silver

        # Create embed
        embed = discord.Embed(
            title=f"🪙 Münzwurf: {result_text}!",
            description=f'"{quote}"\n— Money Boy',
            color=color
        )
        embed.set_image(url=image_url)

        # Add footer based on whether fallback was used
        timestamp = int(time.time())
        if used_fallback:
            embed.set_footer(text=f"⚠️ random.org nicht erreichbar - Python-Zufallsgenerator verwendet • <t:{timestamp}:R>")
        else:
            embed.set_footer(text=f"✓ Powered by random.org • <t:{timestamp}:R>")

        await ctx.send(embed=embed)
