import discord
from redbot.core import commands
import aiohttp
import asyncio
import random
import logging
from datetime import datetime


class FlipView(discord.ui.View):
    """View with a button to flip again"""

    def __init__(self, cog, user_id):
        super().__init__(timeout=3600)  # 1 hour
        self.cog = cog
        self.user_id = user_id
        self.message = None

    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        """Only allow the original command invoker to use the button"""
        if interaction.user.id != self.user_id:
            await interaction.response.send_message(
                "Das ist nicht dein Button, Bro! Mach deinen eigenen Flip.",
                ephemeral=True
            )
            return False
        return True

    @discord.ui.button(label="nomma flippne", style=discord.ButtonStyle.primary)
    async def flip_again_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        """Button callback to flip the coin again"""
        # Flip the coin
        coin_value, used_fallback = await self.cog._flip_coin()

        # Get random Money Boy quote
        quote = random.choice(MONEY_BOY_QUOTES)

        # Create new embed
        embed = self.cog._create_flip_embed(coin_value, quote, used_fallback)

        # Create new view with fresh timeout
        new_view = FlipView(self.cog, self.user_id)
        new_view.message = self.message

        # Update the message
        await interaction.response.edit_message(embed=embed, view=new_view)

    async def on_timeout(self):
        """Disable button when timeout expires"""
        if self.message:
            for item in self.children:
                item.disabled = True
            try:
                await self.message.edit(view=self)
            except discord.errors.NotFound:
                pass  # Message was deleted


# Money Boy quotes - YSL Know Plug Swag Collection
MONEY_BOY_QUOTES = [
    "Dreh den Swag auf, ich bin fresher als du!",
    "YSL Know Plug, du weißt Bescheid!",
    "Gucci, Louis, Prada - das ist mein Lifestyle!",
    "Ich bin am flexen mit dem Drip, verstehst du?",
    "Turn up! Swag swag, 420 Blaze It!",
    "YSL Know Plug mit dem Louis V-Swag!",
    "Gucci Gang, ich bin am drippn, verstehst?",
    "Turn up! 420 Blaze It, Swag auf Maximum!",
    "Ich hab mehr Drip als dein ganzer Squad!",
    "Versace Versace, ich bin so fly!",
    "Gönn dir mal bisschen Swag, Bro!",
    "Was 1 Life! I bims, der Swag-King!",
    "Auf Lock mit dem Gucci-Gürtel, weißt du!",
    "Money Boy in the house, Swag overload!",
    "Ich flex so hard, die Hater haten!",
    "Louis Vuitton auf meinem Body, das ist real!",
    "Drip so hard wie ein Wasserfall, Bro!",
    "YSL ist nicht nur ein Label, ist ein Lifestyle!",
    "Ich bin am shinen wie ein Diamant, Know what I'm sayin?",
    "Swag auf 1000, ich kann nicht anders!",
    "Prada-Schuhe, Gucci-Tasche, Versace-Hemd!",
    "Turn up the Swag, es gibt kein Limit!",
    "Ich bin so fresh, ich brauch keine Werbung!",
    "Money Boy, der Name ist Programm, verstehst?",
    "Drip Check: bestanden mit Auszeichnung!",
    "Gönn dir den Swag, du verdienst es!",
    "Ich rock Designer von Kopf bis Fuß!",
    "YSL Know Plug, immer am Start mit dem Drip!",
    "Swag ist keine Phase, Swag ist Forever!",
    "Ich bin am flexen, während du am haten bist!",
    "Louis Vuitton Monogram überall, das ist mein Markenzeichen!",
    "Dreh den Swag auf Maximum, Bro!",
    "Ich bin so fly, ich brauch kein Flugzeug!",
    "Gucci down, von Kopf bis Fuß!",
    "YSL Know Plug - Remember the name!",
    "Mein Drip ist legendär, frag irgendwen!",
    "Swag swag, ich kann gar nicht anders!",
    "Turn up mit dem Swag, das ist der Way!",
    "Ich bin am shinen, du bist am dimmen!",
    "Versace on me, ich fühl mich wie ein König!",
    "Money Boy Swag, unvergleichlich!",
    "Drip so heavy, ich brauch ne Versicherung!",
    "YSL ist die Attitude, nicht nur die Kleidung!",
    "Ich flex auf einem anderen Level, verstehst?",
    "Gucci Flip Flops und Louis V-Socken!",
    "Swag overload, kann nicht stoppen!",
    "Ich bin fresh to death, literally!",
    "Turn up the Lifestyle, turn up the Swag!",
    "Prada Bag, Gucci Shades, Versace Shirt - that's me!",
    "YSL Know Plug, 24/7 am drippn!",
    "Mein Swag ist ansteckend, Vorsicht!",
    "Ich bin am flexen wie ein Bodybuilder!",
    "Louis Vuitton Drip, jeden Tag!",
    "Swag ist meine Superkraft!",
    "Turn up, ich bin der Swag-Champion!",
    "Gucci Gang Member seit Tag 1!",
    "Ich hab mehr Style als deine Playlist!",
    "YSL Know Plug - The Swag Provider!",
    "Drip Check: immer approved!",
    "Ich bin am shinen wie die Sonne!",
    "Versace Dreams, Gucci Reality!",
    "Money Boy Mode: activated!",
    "Swag Level: über 9000!",
    "Ich flex mit links, easy!",
    "Louis Vuitton ist mein zweiter Vorname!",
    "Turn up the Swag Meter!",
    "Ich bin so fresh, ich könnt in den Kühlschrank!",
    "Gucci on my feet, Louis on my waist!",
    "YSL Know Plug, remember that!",
    "Drip so clean, ich brauch kein Wasser!",
    "Swag swag, das ist mein Mantra!",
    "Ich bin am flexen, während andere schlafen!",
    "Prada Lover, Gucci Believer!",
    "Turn up! Swag ist mein Element!",
    "Ich hab den Drip erfunden, ehrlich!",
    "Versace Versace, I'm so fancy!",
    "YSL Know Plug - Your Swag Dealer!",
    "Money Boy Swag, accept no substitutes!",
    "Ich bin fresher als Morgentau!",
    "Louis Vuitton Pattern in meinen Träumen!",
    "Swag auf Lock, immer!",
    "Turn up the Volume, turn up the Swag!",
    "Gucci Belt so tight, der Swag explodiert!",
    "Ich bin am shinen ohne Filter!",
    "YSL ist nicht nur Kleidung, ist Religion!",
    "Drip Drip Drip, wie ein Wasserhahn!",
    "Ich flex härter als dein Gym-Trainer!",
    "Versace Shirt, Prada Pants, that's the fit!",
    "Money Boy in the Building!",
    "Swag so strong, gravitational pull!",
    "Ich bin am drippn wie nach nem Regenschauer!",
    "Louis Vuitton Drip macht splash!",
    "Turn up! Es ist Swag Time!",
    "Ich hab den Swag auf Autopilot!",
    "Gucci Gucci, Louis Louis, Prada Prada!",
    "YSL Know Plug - Swag Supplier!",
    "Drip Game: undefeated!",
    "Ich bin fresher als frisch gepresster O-Saft!",
    "Swag ist meine DNA!",
    "Turn up the Freshness!",
    "Versace on my body, Swag in my soul!",
    "Ich flex mit Stil und Eleganz!",
    "Money Boy Energy, unbezahlbar!",
    "Louis Vuitton Lifestyle, das bin ich!",
    "Swag swag, every single day!",
    "Ich bin am shinen wie ein Sternenhimmel!",
    "Gucci down, head to toe!",
    "YSL Know Plug - Trust the Process!",
    "Drip so immaculate, museum-worthy!",
    "Turn up! Swag hat keine Grenzen!",
    "Ich hab mehr Swag als ein Swag-Shop!",
    "Prada Drip, Gucci Trip!",
    "Swag Level: Maximum Overdrive!",
    "Ich bin fresher als ein Pfefferminz!",
    "Versace Vibes only!",
    "YSL Know Plug - The Drip Doctor!",
    "Money Boy Swag, patentiert!",
    "Louis Vuitton Love, eternal!",
    "Ich flex und relax gleichzeitig!",
    "Turn up the Swag Engine!",
    "Gucci Glasses, ich seh die Welt in Swag!",
    "Drip so fresh, straight from the source!",
    "Swag auf 100, minimum!",
    "Ich bin am shinen ohne Sonnenschein!",
    "YSL ist mein Kompass im Leben!",
    "Turn up! Swag-O-Clock!",
    "Ich hab den Drip, den du suchst!",
    "Versace Dreams werden wahr!",
    "Money Boy Style, unverwechselbar!",
    "Louis Vuitton Waves, ich reite sie!",
    "Swag swag, non-stop!",
    "Ich bin fresher als der erste Schnee!",
    "Gucci Gang, wir sind am Start!",
    "YSL Know Plug - Swag Architect!",
    "Drip Check bestanden, mit Sternchen!",
    "Turn up! Swag ist angesagt!",
    "Ich flex mit Präzision und Leidenschaft!",
    "Prada on my mind, Gucci on my body!",
    "Swag ist mein Mittlerer Name!",
    "Ich bin am drippn wie ein tropfender Wasserhahn!",
    "Versace Versace, all day every day!",
    "YSL Know Plug - Your Swag Guru!",
    "Money Boy Magic, kann man nicht lernen!",
    "Louis Vuitton Drip, unstoppable!",
    "Swag auf Lock und Key!",
    "Turn up the Drip Meter!",
    "Ich bin so fresh, Fische sind neidisch!",
    "Gucci Shoes, Louis Bag, that's the combo!",
    "YSL ist mein Spirit Animal!",
    "Drip so crazy, sie nennen mich verrückt!",
    "Swag swag, ich lebe es!",
    "Ich bin am shinen wie Goldbarren!",
    "Turn up! Swag Season ist immer!",
    "Versace Shirt macht mich immortal!",
    "Ich flex auf höchstem Niveau!",
    "Money Boy Drip, certified!",
    "Louis Vuitton Pattern überall!",
    "Swag ist mein Lebenselixier!",
    "Ich bin fresher als Morgenluft!",
    "Gucci Belt hält meinen Swag zusammen!",
    "YSL Know Plug - Drip Ambassador!",
    "Turn up! Swag hat das Sagen!",
    "Ich hab den Drip, den sie wollen!",
    "Prada Love, Versace Dreams!",
    "Swag Level: off the charts!",
    "Ich bin am drippn wie Regen!",
    "Versace Versace, ich bin blessed!",
    "YSL Know Plug - The Swag Sensei!",
    "Money Boy Flow, unaufhaltsam!",
    "Louis Vuitton ist mein Trademark!",
    "Swag swag, forever young!",
    "Ich bin so fresh, ich glänze!",
    "Turn up! Es ist Flex Time!",
    "Gucci on repeat, das ist der Vibe!",
    "YSL ist meine Religion!",
    "Drip Game so strong, legendary!",
    "Ich flex wie ein Champion!",
    "Swag ist meine Passion!",
    "Turn up the Freshness Dial!",
    "Versace Drip macht mich unsterblich!",
    "Ich bin am shinen wie Edelsteine!",
    "Money Boy Energy ist ansteckend!",
    "Louis Vuitton Vibes, ich spür sie!",
    "Swag auf Maximum Level!",
    "Ich bin fresher als frische Minze!",
    "Gucci Drip, Louis Swag, Prada Flow!",
    "YSL Know Plug - Swag Connoisseur!",
    "Turn up! Swag Overload incoming!",
    "Ich hab mehr Drip als ein Aquarium!",
    "Prada Pants, Versace Shirt, Gucci Shoes!",
    "Swag ist mein Herzschlag!",
    "Ich bin am drippn ohne Ende!",
    "Versace Dreams, Gucci Schemes!",
    "YSL Know Plug - The Drip King!",
    "Money Boy Lifestyle, luxury!",
    "Louis Vuitton Love ist real!",
    "Swag swag, that's my way!",
    "Ich bin so fresh, ich brauch keine Dusche!",
    "Turn up! Swag explodiert!",
    "Gucci Gang Life, ich lebe es!",
    "YSL ist meine Bestimmung!",
    "Drip so fire, ich bin am brennen!",
    "Ich flex mit Style und Grace!",
    "Swag Level: galaktisch!",
    "Turn up the Swag Frequency!",
    "Versace on me, I feel invincible!",
    "Ich bin am shinen wie Platin!",
    "Money Boy Swag, worldwide!",
    "Louis Vuitton Drip, international!",
    "Swag ist mein Treibstoff!",
    "Ich bin fresher als ein Frühlingstag!",
    "Gucci Vibes, ich fühl sie!",
    "YSL Know Plug - Swag Legend!",
    "Turn up! Swag ist die Antwort!",
    "Ich hab den Drip perfektioniert!",
    "Prada Energy, unstoppable!",
    "Swag swag, it's automatic!",
    "Ich bin am drippn wie nie zuvor!",
    "Versace Versace, pure excellence!",
    "YSL Know Plug - Your Drip Guide!",
    "Money Boy Magic ist real!",
    "Louis Vuitton Pattern ist mein Fingerabdruck!",
    "Swag auf höchster Stufe!",
    "Ich bin so fresh, Blumen verwelken!",
    "Turn up! Swag Revolution!",
    "Gucci down, always!",
    "YSL ist mein Nordstern!",
    "Drip so clean, sterile!",
    "Ich flex wie ein Profi!",
    "Swag ist mein Schicksal!",
    "Turn up the Drip Factor!",
    "Versace Shirt gibt mir Superkräfte!",
    "Ich bin am shinen wie Kristall!",
    "Money Boy Drip, original!",
    "Louis Vuitton Life, ich lebe es!",
    "Swag swag, unstoppable force!",
    "Ich bin fresher als Frühlingsregen!",
    "Gucci Belt, Louis Bag, Prada Shoes!",
    "YSL Know Plug - Drip Master!",
    "Turn up! Swag ist mein Element!",
    "Ich hab mehr Swag als ein Swag-Store!",
    "Prada Drip, Versace Trip, Gucci Flip!",
    "Swag Level: astronomical!",
    "Ich bin am drippn wie ein Wasserfall!",
    "Versace Dreams come true!",
    "YSL Know Plug - The Swag Messiah!",
    "Money Boy Energy, unlimited!",
    "Louis Vuitton Drip, timeless!",
    "Swag ist mein Atem!",
    "Ich bin so fresh, ich könnte ein Parfüm sein!",
    "Turn up! Flex Mode activated!",
    "Gucci Love, ich fühle es!",
    "YSL ist mein Leitstern!",
    "Drip Game on point, always!",
    "Ich flex mit Herz und Seele!",
    "Swag ist meine Kunst!",
    "Turn up the Swag Amplitude!",
    "Versace Vibes durchfluten mich!",
    "Ich bin am shinen wie ein Leuchtturm!",
    "Money Boy Style, iconic!",
    "Louis Vuitton Waves, I'm surfing!",
    "Swag swag, perpetual motion!",
    "Ich bin fresher als frisch gefallener Schnee!",
    "Gucci Gang, forever!",
    "YSL Know Plug - Swag Professor!",
    "Turn up! Drip Explosion!",
    "Ich hab den Drip gemeistert!",
    "Prada Power, unbreakable!",
    "Swag ist mein Puls!",
    "Ich bin am drippn in Perfektion!",
    "Versace Versace, that's my motto!",
    "YSL Know Plug - Your Swag Mentor!",
    "Money Boy Magic, unbeschreiblich!",
    "Louis Vuitton Drip, phenomenal!",
    "Swag auf 420 Level!",
    "Ich bin so fresh, ich strahle!",
    "Turn up! Swag Supremacy!",
    "Gucci on my mind, 24/7!",
    "YSL ist mein Polarstern!",
    "Drip so magnificent, regal!",
    "Ich flex mit Leidenschaft!",
    "Swag ist mein Lebensstil!",
    "Turn up the Freshness Factor!",
    "Versace Energy, powerful!",
    "Ich bin am shinen wie Saphire!",
    "Money Boy Drip, exceptional!",
    "Louis Vuitton Love, forever!",
    "Swag swag, infinite loop!",
    "Ich bin fresher als Frühlingsblumen!",
    "Gucci Drip, non-negotiable!",
    "YSL Know Plug - Drip Virtuoso!",
    "Turn up! Swag Domination!",
    "Ich hab den Drip in meinen Genen!",
    "Prada Style, timeless!",
    "Swag Level: transcendent!",
    "Ich bin am drippn wie Honig!",
    "Versace Dreams, living them!",
    "YSL Know Plug - The Swag Oracle!",
    "Money Boy Flow, majestic!",
    "Louis Vuitton Pattern ist meine Signatur!",
    "Swag ist mein Blut!",
    "Ich bin so fresh, ich könnt Werbung machen!",
    "Turn up! Flex Revolution!",
    "Gucci Life, I'm blessed!",
    "YSL ist mein Schutzengel!",
    "Drip so pristine, flawless!",
    "Ich flex wie ein Kunstwerk!",
    "Swag ist meine Seele!",
    "Turn up the Drip Intensity!",
    "Versace Versace, my religion!",
    "Ich bin am shinen wie Smaragde!",
    "Money Boy Energy, contagious!",
    "Louis Vuitton Drip, monumental!",
    "Swag swag, eternal flame!",
    "Ich bin fresher als ein Bergbach!",
    "Gucci Belt holds my universe together!",
    "YSL Know Plug - Swag Deity!",
    "Turn up! Swag Infinity!",
    "Ich hab mehr Drip als der Ozean!",
    "Prada Dreams, Gucci Reality, Versace Fantasy!",
    "Swag ist mein Universum!",
    "Ich bin am drippn wie Lava!",
    "Versace Energy flows through me!",
    "YSL Know Plug - The Drip Sage!",
    "Money Boy Lifestyle, magnificent!",
    "Louis Vuitton Love ist ewig!",
    "Swag auf göttlichem Level!",
    "Ich bin so fresh, ich bin zeitlos!",
    "Turn up! Swag Apocalypse!",
    "Gucci on repeat, that's the program!",
    "YSL ist mein Schicksal!",
    "Drip so divine, heavenly!",
    "Ich flex wie die Götter!",
    "Swag ist mein Karma!",
    "Turn up the Swag Quotient!",
    "Versace Shirt, I'm immortal!",
    "Ich bin am shinen wie Rubine!",
    "Money Boy Drip, legendary status!",
    "Louis Vuitton Vibes, I embody them!",
    "Swag swag, cosmic energy!",
    "Ich bin fresher als Alpenluft!",
    "Gucci Drip, Prada Flow, Louis Glow!",
    "YSL Know Plug - Swag Philosopher!",
    "Turn up! Drip Dynasty!",
    "Ich hab den Swag zum Quadrat!",
    "Prada Power, Versace Vision!",
    "Swag Level: supernatural!",
    "Ich bin am drippn ohne Limit!",
    "Versace Versace, ich bin gesegnet!",
    "YSL Know Plug - Your Drip Savior!",
    "Money Boy Magic, phenomenal!",
    "Louis Vuitton Pattern ist meine DNA!",
    "Swag ist mein Sauerstoff!",
    "Ich bin so fresh, ich glitzere!",
    "Turn up! Swag Eternity!",
    "Gucci Gang für immer und ewig!",
    "YSL ist mein Lebensweg!",
    "Drip so exquisite, priceless!",
    "Ich flex mit göttlicher Energie!",
    "Swag ist mein Vermächtnis!",
    "Turn up the Drip Magnitude!",
    "Versace Energy, ich bin voll damit!",
    "Ich bin am shinen wie Diamanten auf Steroiden!",
    "Money Boy Swag, unvergleichlich in diesem Universum!",
    "Louis Vuitton Drip, ich schwimme darin!",
    "Swag swag, das ist keine Phase, das ist mein Leben!",
    "Ich bin fresher als ein Neuanfang!",
    "Gucci down von Kopf bis Fuß, keine Kompromisse!",
    "YSL Know Plug - Der Swag-Messias persönlich!",
    "Turn up! Swag bis in die Unendlichkeit und noch weiter!",
    "Ich hab mehr Drip als alle Wasserfälle zusammen!",
    "Prada, Gucci, Versace - die Heilige Dreifaltigkeit!",
    "Swag Level: über allen Wolken!",
    "Ich bin am drippn wie es kein anderer kann!",
    "Versace Dreams sind meine Realität!",
    "YSL Know Plug - The One and Only!",
    "Money Boy Energy durchflutet das ganze Game!",
    "Louis Vuitton ist nicht nur Fashion, ist mein Wesen!",
    "Swag auf 420, always blazing!",
    "Dreh den Swag auf 420, vong Freshness her!",
    "Gucci Flip-Flops am Strand, das ist der Move!",
    "Ich bin der CEO von Swag Incorporated!",
    "YSL Know Plug - Drip Certified seit Tag Null!",
    "Money in der Tasche, Swag in der Seele!",
    "Louis V-Muster überall, das ist mein Signature!",
    "Turn up! Ich bin zu fresh für diese Welt!",
    "Versace Robe, ich fühl mich wie ein Kaiser!",
    "Swag ist keine Option, ist ein Muss!",
    "Ich bin am flexen wie ein Yoga-Lehrer!",
    "Gucci Shades on, ich seh die Welt in Gold!",
    "YSL Know Plug - The Swag Encyclopedia!",
    "Drip so crazy, sie schreiben Bücher drüber!",
    "Money Boy Flow ist wie ein Wasserfall!",
    "Prada Schuhe, jeder Schritt ein Statement!",
    "Swag auf Overdrive, ich kann nicht bremsen!",
    "Ich bin fresher als Morning Dew!",
    "Louis Vuitton Trunk full of Swag!",
    "Turn up! Das ist mein Natural State!",
    "Versace Versace, ich lebe den Traum!",
    "YSL ist mehr als Kleidung, ist Philosophy!",
    "Gucci Belt so tight, der Swag kann nicht raus!",
    "Ich flex automatisch, ist Reflexion!",
    "Swag Level: Breaking the Meter!",
    "Money Boy Magic ist wissenschaftlich bewiesen!",
    "Drip so intense, ich brauch Sonnenschutz!",
    "Ich bin am shinen wie die Vegas Lights!",
    "Prada on my feet, Gucci on repeat!",
    "Turn up the Swag Temperature!",
    "Louis Vuitton Love ist unconditional!",
    "Swag swag, every hour, every day!",
    "Versace Dreams werden Realität bei mir!",
    "YSL Know Plug - Swag Specialist!",
    "Ich bin fresher als der Herbstwind!",
    "Gucci Gang Lifestyle, keine Alternative!",
    "Money Boy Energy ist ansteckend wie Lachen!",
    "Drip Check: Always Excellent!",
    "Swag ist mein Default-Modus!",
    "Ich bin am drippn wie ein Wasserschlauch!",
    "Turn up! Swag ist mein Business!",
    "Louis Vuitton Pattern in meinem Blutkreislauf!",
    "Versace Versace, pure Eleganz!",
    "YSL Know Plug - Your Swag Navigator!",
    "Ich flex mit der Intensität der Sonne!",
    "Prada Power ist unaufhaltsam!",
    "Swag auf Maximum, keine Kompromisse!",
    "Gucci Vibes durchfluten meinen Körper!",
    "Money Boy Swag ist trademark protected!",
    "Ich bin so fresh, ich könnte schweben!",
    "Drip so monumental, UNESCO Weltkulturerbe!",
    "Turn up! Swag Revolution startet jetzt!",
    "Louis Vuitton ist mein Spirit Brand!",
    "Swag swag, infinite possibilities!",
    "Ich bin am shinen wie Polarlichter!",
    "Versace Energy gibt mir Flügel!",
    "YSL Know Plug - The Drip Encyclopedia!",
    "Gucci down, das ist der Standard!",
    "Ich hab mehr Style als ein Fashion-Magazin!",
    "Money Boy Lifestyle ist Premium Quality!",
    "Drip so perfect, symmetrisch und balanced!",
    "Swag ist mein Operating System!",
    "Turn up the Freshness Meter!",
    "Prada Dreams, ich schlaf darin!",
    "Ich bin fresher als Winterluft!",
    "Louis Vuitton Drip, medically approved!",
    "Swag auf 100, minimum Standard!",
    "Versace Versace, ich atme Luxus!",
    "YSL Know Plug - Certified Drip Expert!",
    "Gucci Love ist wahre Liebe, ehrlich!",
    "Ich flex mit mathematischer Präzision!",
    "Money Boy Energy ist renewable!",
    "Drip so fresh, straight out the box!",
    "Swag Level: Stratosphärisch!",
    "Turn up! Ich bin der Swag-Champion!",
    "Ich bin am drippn wie ein Brunnen!",
    "Louis Vuitton Vibes, I feel them!",
    "Prada Power flows through my veins!",
    "Swag swag, das ist die Message!",
    "Versace Dreams, living la vida loca!",
    "YSL Know Plug - Swag Architect Supreme!",
    "Ich bin so fresh, Blumen beneiden mich!",
    "Gucci Gang, we run this town!",
    "Money Boy Swag, international anerkannt!",
    "Drip Check bestanden mit Sternchen und Sterne!",
    "Swag ist meine Muttersprache!",
    "Turn up! Flexing ist mein Workout!",
    "Ich bin am shinen wie ein Kristallpalast!",
    "Louis Vuitton Love, forever and ever!",
    "Prada on my mind, 24/7/365!",
    "Swag auf Turbo-Modus!",
    "Versace Versace, ich bin illuminated!",
    "YSL Know Plug - The One True Swag King!",
    "Ich bin fresher als ein Sommerregen!",
    "Gucci Drip macht mich unsterblich!",
    "Money Boy Energy ist wie Elektrizität!",
    "Drip so immaculate, gallery-worthy!",
    "Swag Level: Off the Richter Scale!",
    "Turn up the Drip Amplifier!",
    "Ich flex mit kosmischer Energie!",
    "Louis Vuitton Pattern ist mein Wallpaper!",
    "Swag swag, perpetual excellence!",
    "Prada Power, unlimited edition!",
    "Versace Dreams sind meine Realität!",
    "YSL Know Plug - Drip Maestro!",
    "Ich bin am drippn wie Niagara Falls!",
    "Gucci Love ist für immer!",
    "Money Boy Swag, made in Austria!",
    "Drip so fire, ich bin am brennen literally!",
    "Swag ist mein Sixth Sense!",
    "Turn up! Das ist mein Lebensmotto!",
    "Ich bin so fresh, ich strahle UV-Licht!",
    "Louis Vuitton Drip, approved by NASA!",
    "Prada Energy ist nuklear!",
    "Swag auf Warp Speed!",
    "Versace Versace, ich bin transcendent!",
    "YSL Know Plug - Your Daily Drip Dose!",
    "Ich bin am shinen wie ein Supernova!",
    "Gucci Gang Mentality, always!",
    "Money Boy Magic ist peer-reviewed!",
    "Drip so legendary, myth status!",
    "Swag Level: Dimension X!",
    "Turn up the Swag Reactor!",
    "Ich flex mit galaktischer Power!",
    "Louis Vuitton Love ist mein Fundament!",
    "Swag swag, eternal flame burning!",
    "Prada Dreams werden wahr, believe it!",
    "Ich bin fresher als Rosentau!",
    "Versace Energy ist mein Kraftstoff!",
    "YSL Know Plug - Swag Professor Emeritus!",
    "Gucci down, always and forever!",
    "Ich bin am drippn in 4K Ultra HD!",
    "Money Boy Swag, patentiert und zertifiziert!",
    "Drip so clean, hospital-grade!",
    "Swag ist meine Superkraft, kein Scherz!",
    "Turn up! Ich bin der Swag-Botschafter!",
    "Louis Vuitton Drip, pharmaceutical quality!",
    "Prada Power ist meine Geheimwaffe!",
    "Swag auf Super-Saiyan Level!",
    "Ich bin so fresh, ich könnte fliegen!",
    "Versace Versace, blessed and highly favored!",
    "YSL Know Plug - The Drip Whisperer!",
    "Gucci Love brennt ewig!",
    "Ich flex mit der Power von tausend Sonnen!",
    "Money Boy Energy ist contagious!",
    "Drip so magnificent, royalty approved!",
    "Swag Level: Intergalactic!",
    "Turn up the Freshness Cannon!",
    "Ich bin am shinen wie die Milchstraße!",
    "Louis Vuitton Vibes, permanent residence!",
    "Swag swag, no days off!",
    "Prada on repeat, infinite loop!",
    "Ich bin fresher als der Ozean!",
    "Versace Dreams sind sweet wie Honig!",
    "YSL Know Plug - Certified Swag Genius!",
    "Gucci Gang forever, never ending!",
    "Ich bin am drippn wie ein Regenschauer!",
    "Money Boy Swag, UNESCO protected!",
    "Drip so divine, angel-approved!",
    "Swag ist mein Element, wie Wasser!",
    "Turn up! Ich bin die Swag-Legende!",
    "Louis Vuitton Love ist unbreakable!",
    "Prada Power, maximum overdrive!",
    "Swag auf Hyperdrive!",
    "Ich bin so fresh, ich glühe!",
    "Versace Versace, ich bin enlightened!",
    "YSL Know Plug - The Ultimate Drip Authority!",
    "Gucci Drip for breakfast, lunch and dinner!",
    "Ich flex mit göttlicher Präzision!",
    "Money Boy Energy ist radioactive!",
    "Drip so perfect, mathematically proven!",
    "Swag Level: Beyond Comprehension!",
    "Turn up the Swag Turbo!",
    "Ich bin am shinen wie ein Leuchtfeuer!",
    "Louis Vuitton Pattern ist mein Herzschlag!",
    "Swag swag, astronomical levels!",
    "Prada Dreams, ich lebe drin!",
    "Ich bin fresher als Gletscherwasser!",
    "Versace Energy durchströmt mich!",
    "YSL Know Plug - Swag Scientist!",
    "Gucci Love ist meine Religion!",
    "Ich bin am drippn wie ein Geysir!",
    "Money Boy Swag, world heritage!",
    "Drip so exquisite, museum quality!",
    "Swag ist in meinem genetic code!",
    "Turn up! Flexing ist meine Berufung!",
    "Louis Vuitton Drip, platinum certified!",
    "Prada Power ist mein Benzin!",
    "Swag auf Ultra-Instinct!",
    "Ich bin so fresh, ich bin legendary!",
    "Versace Versace, divinely inspired!",
    "YSL Know Plug - The Swag Oracle Supreme!",
    "Gucci Gang, worldwide domination!",
    "Ich flex mit universeller Energie!",
    "Money Boy Magic ist scientific fact!",
    "Drip so pristine, laboratory tested!",
    "Swag Level: Multidimensional!",
    "Turn up the Drip Matrix!",
    "Ich bin am shinen wie Aurora Borealis!",
    "Louis Vuitton Love ist eternal truth!",
    "Swag swag, never-ending story!",
    "Prada on my soul, deep rooted!",
    "Ich bin fresher als Quellwasser!",
    "Versace Dreams sind crystal clear!",
    "YSL Know Plug - Master of Swag Arts!",
    "Gucci down, certified authentic!",
    "Ich bin am drippn in Ultra-HD!",
    "Money Boy Swag, globally recognized!",
    "Drip so heavenly, celestial approved!",
    "Swag ist mein Birthright!",
    "Turn up! Ich bin der Drip-Kaiser!",
    "Louis Vuitton Drip, divine intervention!",
    "Prada Power ist unstoppable force!",
    "Swag auf Infinity-Modus!",
    "Ich bin so fresh, ich bin timeless!",
    "Versace Versace, eternally blessed!",
    "YSL Know Plug - Swag Grandmaster!",
    "Gucci Love burns forever bright!",
    "Ich flex mit der Kraft des Universums!",
    "Money Boy Energy ist legendary status!",
    "Drip so magnificent, Nobel Prize worthy!",
    "Swag Level: Transcendent Reality!",
    "Turn up the Freshness Supernova!",
    "Ich bin am shinen wie alle Sterne zusammen!",
    "Louis Vuitton Vibes, embedded in DNA!",
    "Swag swag, infinity and beyond!",
    "Prada Dreams materialize daily!",
    "Ich bin fresher als der Himmel!",
    "Versace Energy ist my life force!",
    "YSL Know Plug - Supreme Drip Commander!",
    "Gucci Gang, eternal legacy!",
    "Ich bin am drippn wie ein Ozean!",
    "Money Boy Swag, world-class standard!",
    "Drip so immaculate, perfection achieved!",
    "Swag ist mein Destiny!",
    "Turn up! Das ist mein Purpose!",
    "Louis Vuitton Love conquers all!",
    "Prada Power, keine Grenzen!",
    "Swag auf God-Level!",
    "Ich bin so fresh, ich bin mythical!",
    "Versace Versace, heavenly ordained!",
    "YSL Know Plug - The Drip Messiah Returns!",
    "Gucci Drip, morning noon and night!",
    "Ich flex mit biblischen Proportionen!",
    "Money Boy Energy ist infinite resource!",
    "Drip so fire, volcano status!",
    "Swag Level: Cosmic Consciousness!",
    "Turn up the Swag Infinity!",
    "Ich bin am shinen wie das ganze Universum!",
    "Louis Vuitton Pattern ist sacred geometry!",
    "Swag swag, eternal manifestation!",
    "Prada on my mind, meditation style!",
    "Ich bin fresher als alle Elements!",
    "Versace Dreams sind prophetic visions!",
    "YSL Know Plug - Absolute Swag Authority!",
    "Gucci Love ist universal law!",
    "Ich bin am drippn wie Naturgewalt!",
    "Money Boy Swag, astronomical phenomenon!",
    "Drip so legendary, history books!",
    "Swag ist mein Raison d'être!",
    "Turn up! Ich bin der Alpha Drip!",
    "Louis Vuitton Drip, cosmically aligned!",
    "Prada Power ist mein Chi!",
    "Swag auf Omnipotent-Level!",
    "Ich bin so fresh, ich bin eternal!",
    "Versace Versace, universally blessed!",
    "YSL Know Plug - The One Above All!",
    "Ich hab den Drip mit Zertifikat!",
    "Gucci, Prada, Louis - die Trinity!",
    "Money Boy Modus ist always on!",
    "Swag auf Raketen-Speed!",
    "Ich bin fresher als frisch gebrühter Kaffee!",
    "YSL Know Plug with the golden touch!",
    "Drip so crazy, they study it!",
    "Turn up! Swag ist keine Phase!",
    "Louis Vuitton überall, das ist normal!",
    "Ich flex so natural wie atmen!",
    "Versace Vibes sind mein Adrenalin!",
    "Swag swag, ich bin der Boss!",
    "Gucci Gang, we worldwide!",
    "Money Boy Energy nie am Ende!",
    "Prada on my feet, walking on clouds!",
    "Ich bin am shinen wie Glühwürmchen!",
    "Drip Check: Permanent A+!",
    "Swag ist mein Trademark!",
    "YSL Know Plug - Drip Innovator!",
    "Turn up the Volume und den Swag!",
    "Louis Vuitton Flow wie ein River!",
    "Ich bin so fresh, ich bin unstoppable!",
    "Gucci Drip vom Scheitel bis zur Sohle!",
    "Money Boy Swag, original recipe!",
    "Versace Versace, das ist Qualität!",
    "Swag auf Premium-Level!",
    "Ich flex mit Style und Substanz!",
    "Prada Power gibt mir Energy!",
    "Drip so clean, Operating Room steril!",
    "YSL ist mein Guiding Light!",
    "Turn up! Ich bin am Start!",
    "Swag swag, von morgens bis abends!",
    "Ich bin fresher als Minze!",
    "Louis Vuitton Drip ist mein Signature Move!",
    "Gucci Love, ich fühl es deep!",
    "Money Boy Energy ist my fuel!",
    "Ich bin am drippn wie crazy!",
    "Versace Dreams sind vivid und real!",
    "Swag Level übertrifft Erwartungen!",
    "YSL Know Plug - Always Delivering!",
    "Turn up the Swag Amplifier!",
    "Prada Pants, Gucci Shirt, perfekte Kombo!",
    "Ich bin so fresh, Früchte sind jealous!",
    "Drip so fire, Feuerwehr on standby!",
    "Swag ist mein Daily Bread!",
    "Louis Vuitton Love ist pure!",
    "Ich flex automatisch, Autopilot mode!",
    "Gucci Gang Lifestyle, no regrets!",
    "Money Boy Swag, carefully crafted!",
    "Versace Versace, ich leb den Dream!",
    "Turn up! Swag ist mein Game!",
    "YSL Know Plug mit dem Golden Drip!",
    "Ich bin am shinen wie Edelmetalle!",
    "Prada Energy ist my power source!",
    "Swag swag, konstant und consistent!",
    "Drip Check ergibt immer top score!",
    "Louis Vuitton Pattern ist my blueprint!",
    "Ich bin fresher als Ocean Breeze!",
    "Gucci Drip ist mein Lebensstil!",
    "Money Boy Energy, fully charged!",
    "Swag auf Executive Level!",
    "Versace Dreams inspire mich daily!",
    "Turn up! Ich bin der Drip-Master!",
    "YSL Know Plug - Premium Quality!",
    "Ich flex mit Eleganz und Power!",
    "Prada on my mind like meditation!",
    "Swag ist my natural state!",
    "Louis Vuitton Drip, handcrafted!",
    "Ich bin so fresh, I'm magnetic!",
    "Gucci Love ist unconditional!",
    "Money Boy Swag, finely tuned!",
    "Drip so intense, UV-Protection needed!",
    "Versace Versace, pure excellence!",
    "Turn up the Swag Frequency!",
    "YSL ist my North Star!",
    "Swag swag, never fading!",
    "Ich bin am drippn wie ein Pro!",
    "Prada Power ist renewable energy!",
    "Louis Vuitton Love, deeply rooted!",
    "Ich bin fresher als Mountain Air!",
    "Gucci Gang, we unstoppable!",
    "Money Boy Energy durchflutet alles!",
    "Swag Level höher als Everest!",
    "Drip so perfect, engineered!",
    "Turn up! Flexing ist Art!",
    "Versace Dreams werden Reality!",
    "YSL Know Plug - Quality Guaranteed!",
    "Ich bin am shinen perpetually!",
    "Swag ist mein Identity!",
    "Louis Vuitton Drip, expertly crafted!",
    "Prada on my body, in my spirit!",
    "Ich flex mit Purpose und Passion!",
    "Gucci Drip ist fundamentals!",
    "Money Boy Swag, thoroughly tested!",
    "Versace Versace, divinely blessed!",
    "Turn up the Drip Intensity!",
    "Swag swag, morning and night!",
    "YSL Know Plug delivering excellence!",
    "Ich bin so fresh, ich bin limitless!",
    "Louis Vuitton Love ist mein Foundation!",
    "Drip Check zeigt Perfect Score!",
    "Prada Energy flows naturally!",
    "Swag auf Master-Level!",
    "Ich bin am drippn effortlessly!",
    "Gucci Love ist my motivation!",
    "Money Boy Energy ist contagious!",
    "Versace Dreams sind spectacular!",
    "Turn up! Swag ist my calling!",
    "YSL ist my guiding principle!",
    "Swag swag, authentic und real!",
    "Ich bin fresher als Crystal Water!",
    "Louis Vuitton Drip, meticulously designed!",
    "Prada Power ist unstoppable!",
    "Ich flex mit Confidence und Style!",
    "Gucci Gang representing worldwide!",
    "Money Boy Swag, premium edition!",
    "Drip so clean, sanitized!",
    "Versace Versace, eternally fresh!",
    "Turn up the Freshness Factor!",
    "YSL Know Plug - Consistency King!",
    "Swag Level breaks all records!",
    "Ich bin am shinen brilliantly!",
    "Louis Vuitton Love ist everlasting!",
    "Prada on my mind constantly!",
    "Swag ist my signature!",
    "Ich bin so fresh, timeless classic!",
    "Gucci Drip jeden Tag!",
    "Money Boy Energy ist limitless!",
    "Drip so fire, thermometer explodes!",
    "Versace Dreams manifest reality!",
    "Turn up! Ich bin the Standard!",
    "YSL Know Plug setting trends!",
    "Swag swag, unmatched quality!",
    "Louis Vuitton Drip, handpicked!",
    "Ich flex naturally, it's innate!",
    "Prada Energy ist my essence!",
    "Swag auf Supreme-Level!",
    "Ich bin fresher als Alpine Snow!",
    "Gucci Love burns eternal!",
    "Money Boy Swag, perfected formula!",
    "Versace Versace, absolutely flawless!",
    "Turn up the Drip Quotient!",
    "YSL ist my life philosophy!",
    "Drip Check always exceptional!",
    "Swag ist my everything!",
    "Ich bin am drippn magnificently!",
    "Louis Vuitton Love ist powerful!",
    "Prada on my soul permanently!",
    "Ich bin so fresh, I'm revolutionary!",
    "Gucci Gang, legacy builders!",
    "Money Boy Energy ist infectious!",
    "Swag Level astronomical heights!",
    "Versace Dreams so vivid!",
    "Turn up! Swag ist eternal!",
    "YSL Know Plug - Excellence Personified!",
    "Ich flex mit Precision und Power!",
    "Louis Vuitton Drip, artisan quality!",
    "Swag swag, forever und always!",
    "Prada Power ist my strength!",
    "Drip so legendary, epic tales!",
    "Ich bin fresher than fresh itself!",
    "Gucci Drip ist my lifestyle!",
    "Money Boy Swag, hall of fame!",
    "Versace Versace, peak performance!",
    "Turn up the Swag Millennium!",
    "YSL ist my compass!",
    "Swag ist mein Masterpiece!",
    "Ich bin der Swag-Architekt, ich baue Imperien!",
    "Louis Vuitton Dreams every night!",
    "Gucci Socks, das Detail macht's!",
    "Money Boy Vibes sind elektrisierend!",
    "Drip so consistent, wie ein Schweizer Uhrwerk!",
    "Swag auf Stereo, links und rechts!",
    "YSL Know Plug - Immer authentisch!",
    "Ich bin fresher als Winterschnee!",
    "Prada Lifestyle, keine Kompromisse!",
    "Turn up! Drip ist mein Programm!",
    "Versace Versace, ich bin gestyled!",
    "Swag swag, das ist mein Weg!",
    "Gucci Gang, family forever!",
    "Ich flex mit Herzenslust!",
    "Louis Vuitton Pattern everywhere I go!",
    "Money Boy Energy ist pure Motivation!",
    "Drip Level: Expertenmodus!",
    "Swag ist mein Handwerk!",
    "YSL Know Plug - Der Drip-Profi!",
    "Turn up! Ich bin voll dabei!",
    "Ich bin so fresh, unwiderstehlich!",
    "Prada on my mind, Gucci on my grind!",
    "Versace Energy ist pure Power!",
    "Swag auf Highspeed!",
    "Gucci Love läuft deep!",
    "Ich bin am shinen wie Kristall!",
    "Louis Vuitton Drip, hand-selected!",
    "Money Boy Swag, limited edition!",
    "Drip so clean, klinisch rein!",
    "Turn up the Swag Revolution!",
    "YSL ist mein Lebenselixir!",
    "Swag swag, ohne Pause!",
    "Ich bin fresher als Sommerwind!",
    "Prada Power, full throttle!",
    "Versace Versace, ich bin outstanding!",
    "Gucci Drip rund um die Uhr!",
    "Ich flex mit vollem Einsatz!",
    "Money Boy Energy, never ending!",
    "Swag Level: Meisterklasse!",
    "Louis Vuitton Love ist stark!",
    "Turn up! Drip Mode aktiviert!",
    "YSL Know Plug - Premium Service!",
    "Ich bin am drippn professionell!",
    "Swag ist mein Kapital!",
    "Prada Dreams sind meine Inspiration!",
    "Gucci Gang, wir sind stark!",
    "Ich bin so fresh, magnetic!",
    "Versace Energy durchströmt mein Sein!",
    "Money Boy Swag, top quality!",
    "Drip so fire, heiß und heavy!",
    "Turn up! Swag ist mein Motto!",
    "Louis Vuitton Drip, carefully curated!",
    "Swag swag, Tag für Tag!",
    "YSL ist my everything!",
    "Ich bin fresher als Regentropfen!",
    "Prada Power gibt mir Kraft!",
    "Gucci Love ist mein Antrieb!",
    "Ich flex mit Überzeugung!",
    "Versace Versace, ich bin brilliant!",
    "Money Boy Energy ist my vibe!",
    "Swag Level: Höchststufe erreicht!",
    "Turn up the Drip Power!",
    "Louis Vuitton Pattern ist iconic!",
    "YSL Know Plug - Immer on point!",
    "Ich bin am shinen wie Gold!",
    "Swag ist mein Fundament!",
    "Prada on my back, Gucci in my heart!",
    "Drip Check: Immer positiv!",
    "Ich bin so fresh, incredible!",
    "Gucci Gang Mentality ist real!",
    "Money Boy Swag, world famous!",
    "Versace Dreams führen mich!",
    "Turn up! Swag ohne Ende!",
    "Louis Vuitton Drip, feinste Qualität!",
    "Swag swag, unaufhörlich!",
    "YSL ist my sanctuary!",
    "Ich bin fresher als Tau am Morgen!",
    "Prada Power ist explosiv!",
    "Gucci Love forever strong!",
    "Ich flex mit ganzer Kraft!",
    "Money Boy Energy ist dynamisch!",
    "Versace Versace, ich bin on fire!",
    "Swag Level über dem Durchschnitt!",
    "Turn up the Freshness Level!",
    "YSL Know Plug - Der Beste!",
    "Ich bin am drippn spectacular!",
    "Louis Vuitton Love ist mächtig!",
    "Swag ist mein daily routine!",
    "Prada Dreams werden gelebt!",
    "Gucci Drip ist essential!",
    "Ich bin so fresh, sensational!",
    "Money Boy Swag, top tier!",
    "Drip so intense, spürbar!",
    "Versace Energy ist elektrisierend!",
    "Turn up! Swag ist meine Art!",
    "Louis Vuitton Drip, exquisit!",
    "Swag swag, ununterbrochen!",
    "YSL ist my inspiration!",
    "Ich bin fresher als klares Wasser!",
    "Prada Power flows constant!",
    "Gucci Love ist authentisch!",
    "Ich flex mit Begeisterung!",
    "Money Boy Energy ist anregend!",
    "Versace Versace, ich bin magnificent!",
    "Swag Level: Profi-Liga!",
    "Turn up the Drip Energy!",
    "YSL Know Plug - Zuverlässig!",
    "Ich bin am shinen wie Silber!",
    "Louis Vuitton Pattern ist klassisch!",
    "Swag ist my daily dose!",
    "Prada on my mind, always!",
    "Gucci Gang, together strong!",
    "Ich bin so fresh, phenomenal!",
    "Money Boy Swag, erste Klasse!",
    "Drip so clean, makellos!",
    "Versace Dreams sind lebendig!",
    "Turn up! Swag ist präsent!",
    "Louis Vuitton Drip, handverlesen!",
    "Swag swag, durchgehend!",
    "YSL ist my foundation!",
    "Ich bin fresher als Frühlingsblüten!",
    "Prada Power ist konstant!",
    "Gucci Love brennt hell!",
    "Ich flex mit Leidenschaft pur!",
    "Money Boy Energy ist mitreißend!",
    "Versace Versace, ich bin fabulous!",
    "Swag Level: Champion-Status!",
    "Turn up the Swag Presence!",
    "YSL Know Plug - Nummer Eins!",
    "Ich bin am drippn outstanding!",
    "Louis Vuitton Love ist beständig!",
    "Swag ist my lifestyle choice!",
    "Prada Dreams inspirieren täglich!",
    "Gucci Drip ist notwendig!",
    "Ich bin so fresh, remarkable!",
    "Money Boy Swag, Spitzenklasse!",
    "Drip so fire, brennend heiß!",
    "Versace Energy ist kraftvoll!",
    "Turn up! Swag dominiert!",
    "Louis Vuitton Drip, erlesen!",
    "Swag swag, permanent aktiv!",
    "YSL ist my guiding force!",
    "Ich bin fresher als Gebirgsluft!",
    "Prada Power läuft smooth!",
    "Gucci Love ist tief verwurzelt!",
    "Ich flex mit Hingabe!",
    "Money Boy Energy ist packend!",
    "Versace Versace, ich bin glorious!",
    "Swag Level: Elite-Klasse!",
    "Turn up the Drip Magnitude!",
    "YSL Know Plug - Unschlagbar!",
    "Ich bin am shinen wie Bronze!",
    "Louis Vuitton Pattern ist zeitlos!",
    "Swag ist my constant companion!",
    "Prada on my soul, tief drin!",
    "Gucci Gang, united we stand!",
    "Ich bin so fresh, extraordinary!",
    "Money Boy Swag, Luxus pur!",
    "Drip so clean, picobello!",
    "Versace Dreams sind real!",
    "Turn up! Swag regiert!",
    "Louis Vuitton Drip, vom Feinsten!",
    "Swag swag, niemals stoppen!",
    "YSL ist my anchor!",
    "Ich bin fresher als Meeresluft!",
    "Prada Power ist beständig!",
    "Gucci Love flammt ewig!",
    "Ich flex mit vollem Herzen!",
    "Money Boy Energy ist fesselnd!",
    "Versace Versace, ich bin splendid!",
    "Swag Level: Königsklasse!",
    "Turn up the Freshness Quotient!",
    "YSL Know Plug - Konkurrenzlos!",
    "Ich bin am drippn exceptional!",
    "Louis Vuitton Love hält ewig!",
    "Swag ist my signature move!",
    "Prada Dreams leben in mir!",
    "Gucci Drip ist unerlässlich!",
    "Ich bin so fresh, spectacular!",
    "Money Boy Swag, Premium-Qualität!",
    "Drip so intense, fühlbar stark!",
    "Versace Energy durchflutet alles!",
    "Turn up! Swag siegt immer!",
    "Louis Vuitton Drip, ausgewählt!",
    "Swag swag, always on!",
    "YSL ist my rock!",
    "Money Boy für immer, Swag bis zum Mond!",
    "Turn up! 1000 Quotes, 1000 Prozent Drip!",
]


class FlipFlopDerCoinBot(commands.Cog):
    """Coin flip with random.org and Money Boy quotes"""

    def __init__(self, bot):
        self.bot = bot
        self.log = logging.getLogger("red.flipflopdercoinbot")

    @commands.command()
    async def flip(self, ctx):
        """Flip a coin (Kopf oder Zahl) with Money Boy swag!"""
        async with ctx.typing():
            # Flip the coin
            coin_value, used_fallback = await self._flip_coin()

            # Get random Money Boy quote
            quote = random.choice(MONEY_BOY_QUOTES)

            # Send result embed
            await self._send_flip_result(ctx, coin_value, quote, used_fallback)

    async def _flip_coin(self):
        """Flip coin using random.org with fallback. Returns (int, bool) - coin value and whether fallback was used"""
        url = "https://www.random.org/integers/?num=1&min=0&max=1&col=1&base=10&format=plain&rnd=new"

        try:
            async with aiohttp.ClientSession() as session:
                timeout = aiohttp.ClientTimeout(total=5)
                async with session.get(url, timeout=timeout) as response:
                    if response.status == 200:
                        result = await response.text()
                        coin_value = int(result.strip())
                        self.log.debug(f"random.org returned: {coin_value}")
                        return (coin_value, False)
                    else:
                        self.log.warning(f"random.org returned HTTP {response.status}, using fallback")
                        return (random.randint(0, 1), True)
        except aiohttp.ClientError as e:
            self.log.error(f"random.org client error: {e}, using fallback")
            return (random.randint(0, 1), True)
        except asyncio.TimeoutError:
            self.log.warning("random.org timeout after 5 seconds, using fallback")
            return (random.randint(0, 1), True)
        except Exception as e:
            self.log.error(f"Unexpected error during coin flip: {e}, using fallback")
            return (random.randint(0, 1), True)

    def _create_flip_embed(self, coin_value, quote, used_fallback):
        """Create embed for coin flip result"""
        # Determine result text, image, and color
        if coin_value == 1:
            result_text = "Kopf"
            image_url = "https://files.catbox.moe/s26vl3.png"
            color = discord.Color.gold()
        else:
            result_text = "Zahl"
            image_url = "https://files.catbox.moe/x1kwoa.png"
            color = discord.Color.from_rgb(192, 192, 192)  # Silver

        # Create embed
        embed = discord.Embed(
            title=f"🪙 Münzwurf: {result_text}!",
            description=f'Der Boy findet:\n"{quote}"',
            color=color
        )
        embed.set_image(url=image_url)

        # Add footer based on whether fallback was used
        timestamp = datetime.now().strftime("%H:%M:%S")
        if used_fallback:
            embed.set_footer(text=f"⚠️ random.org nicht erreichbar - Python-Zufallsgenerator verwendet • {timestamp}")
        else:
            embed.set_footer(text=f"✓ Powered by random.org • {timestamp}")

        return embed

    async def _send_flip_result(self, ctx, coin_value, quote, used_fallback):
        """Send embed with coin flip result"""
        embed = self._create_flip_embed(coin_value, quote, used_fallback)

        # Create view with button
        view = FlipView(self, ctx.author.id)
        message = await ctx.send(embed=embed, view=view)
        view.message = message
